[package]
name = "storage"
version.workspace = true
edition.workspace = true

[dependencies]
domain.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
rusqlite.workspace = true

[dev-dependencies]
repo-scanner = { path = "../repo-scanner" }
claude-parser = { path = "../claude-parser" }
git2.workspace = true
tempfile = "3"
